### ISSUE TITLE
IPoE module fails to build in kernel since 6.12

### ISSUE THREAD

**Issue by axe-kenig** [accel-ppp/accel-ppp#217]
NETIF_F_NETNS_LOCAL is absent in new linux kernel

-NETIF_F_NETNS_LOCAL
+dev->netns_local

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=05c1280a2bcfca187fe7fa90bb240602cf54af0a

[ 99%] Built target accel-pppd
/root/accel-ppp/build/drivers/ipoe/driver/ipoe.c: In function ‘ipoe_netdev_setup’:
/root/accel-ppp/build/drivers/ipoe/driver/ipoe.c:1108:27: error: ‘NETIF_F_NETNS_LOCAL’ undeclared (first use in this function)
 1108 |         dev->features  |= NETIF_F_NETNS_LOCAL;
      |                           ^~~~~~~~~~~~~~~~~~~
/root/accel-ppp/build/drivers/ipoe/driver/ipoe.c:1108:27: note: each undeclared identifier is reported only once for each function it appears in
make[5]: *** [scripts/Makefile.build:229: /root/accel-ppp/build/drivers/ipoe/driver/ipoe.o] Error 1
make[4]: *** [/usr/src/linux-6.12.1-gentoo/Makefile:1936: /root/accel-ppp/build/drivers/ipoe/driver] Error 2
make[3]: *** [Makefile:224: __sub-make] Error 2
make[2]: *** [drivers/ipoe/CMakeFiles/ipoe_drv.dir/build.make:78: drivers/ipoe/driver/ipoe.ko] Error 2
make[1]: *** [CMakeFiles/Makefile2:1497: drivers/ipoe/CMakeFiles/ipoe_drv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking C shared library libipoe.so
[100%] Built target ipoe
[100%] Built target vlan_mon_drv
make: *** [Makefile:156: all] Error 2
